### ISSUE TITLE
Request body

### ISSUE THREAD

**Issue by Indeoo** [null-routed/debank-hash-sign-v2#3]
Hi there,
for me this code seems to work pretty well for get requests with params or post requests without body, but is it possible to add POST body support?
I've tried something like this:
```const requestParams = `${requestMethod.toUpperCase()}\n${path.toLowerCase()}\n${queryParams}\n${body}`;```

Where body is like
`const body = JSON.stringify(
    {
        id: "0xe111111aa6d1485dd4204e86436fc9acda4111b3",
        chain_id: "59144"
    }
)`
but it's not working.
Is it me doing something wrong, or code does not support request body?
if im wrong, can you give example with POST body pls?

**Comment by null-routed** [comment]
Hey, to be fair I haven't looked into POST requests. I should have some free time next week and I could look into it. If it doesn't require too much time - which it shouldn't - I will push an update.

**Comment by Antorchik** [comment]
As I understand it, for POST a lot depends on the request address. Let's say there is an address in the request body of which you specify {"enable":false}, when signing in "parameters" you do not specify anything and a valid signature is generated. But if you use another request, then this trick will not work, that is, you need to specify something in "parameters".

**Comment by null-routed** [comment]
Please provide me with some details on how to trigger the post requests that you mentioned and I'll look into it

**Comment by Antorchik** [comment]
Вот код, пришлось через chatgpt обработать. Но он работает:
>
> import hashlib
> import hmac
> import time
> import random
> import string
> import requests
> import json


def sort_query_string(query_string):
    params = query_string.split("&")
    sorted_params = sorted(params, key=lambda x: x.split("=")[0])
    sorted_query_string = "&".join(sorted_params)
    return sorted_query_string

def sha256(data):
    return hashlib.sha256(data.encode()).hexdigest()

def generate_nonce(length=40):
    characters = string.ascii_letters + string.digits
    nonce = ''.join(random.choice(characters) for _ in range(length))
    return "n_" + nonce

def hmac_sha256(key, data):
    return hmac.new(key.encode(), data.encode(), hashlib.sha256).hexdigest()

def generate_signature(request_method, path, parameters):
    nonce = generate_nonce()
    timestamp = int(time.time())
    rand_str = f"debank-api\n{nonce}\n{timestamp}"
    rand_str_hash = sha256(rand_str)
    request_params =
f"{request_method.upper()}\n{path.lower()}\n{sort_query_string(parameters.lower())}"
    request_params_hash = sha256(request_params)
    signature = hmac_sha256(rand_str_hash, request_params_hash)

    return {
        'nonce': nonce,
        'timestamp': timestamp,
        'signature': signature
    }

# Генерация данных подписи
signature_data = generate_signature(
    "POST",
    "/user/update_enable_notification",
    ""
)

# Заголовки запроса
headers = {
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language":
"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh;q=0.5",
    "origin": "https://debank.com",
    "priority": "u=1, i",
    "referer": "https://debank.com/",
    "sec-ch-ua": '"Not)A;Brand";v="99", "Google Chrome";v="127",
"Chromium";v="127"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "source": "web",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "x-api-nonce": signature_data['nonce'],
    "x-api-sign": signature_data['signature'],
    "x-api-ts": str(signature_data['timestamp']),
    "x-api-ver": "v2",
    "x-trans-language": "RU",
    "Content-Type": "application/json"  # Установка Content-Type для JSON
}

# URL и тело запроса
url = "https://api.debank.com/user/update_enable_notification"
data = {
    "enable": False  # Тело запроса
}

# Отправка POST-запроса
response = requests.post(url, headers=headers, data=json.dumps(data))

# Вывод результата в лог
print(f"Статус код ответа: {response.status_code}")
print(f"Тело ответа: {response.text}")

вт, 13 авг. 2024 г. в 15:09, Nick ***@***.***>:

**Comment by Antorchik** [comment]
But it works the fastest because there is an exception for it in the code, I just saw a script that mentions "/user/update_enable_notification"

**Comment by null-routed** [comment]
Debugging the javascript code, it looks like the POST body is not involved in the signing process. This is the string being hashed when performing the POST request you mentioned. 
![image](https://github.com/user-attachments/assets/7aed11c0-7807-4e97-a9ec-5c4ec46e9769)


> But it works the fastest because there is an exception for it in the code, I just saw a script that mentions "/user/update_enable_notification"

I am not sure what you mean by this
